import type { Metadata } from 'next';
import '@/styles/globals.css';
import { FC } from 'react';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode,
}>;

const RootLayout: FC<RootLayoutProps> = ({
  children,
}) => {
  return (
    <html lang="fr">
    <body>
    {children}
    <Toaster />
    </body>
    </html>
  );
}

export default RootLayout;